### PR TITLE
Create Unspent

### PR DESCRIPTION
**Pull request by anonymeenligne**

### CODE REVIEW

**Comment by cculianu** [comment]
Can you please not make a pull request and actually create an issue?  This is not how github works.

**Comment by cculianu** [comment]
Also please create an issue on the actual main repo: https://github.com/Electron-Cash/Electron-Cash

**Comment by anonymeenligne** [comment]
I m sorry
i try to get an issue to my problem and as you can see i m a beginner and not expert!! sorry sorry sorry
i just want to ask if you can help me with electron-cash wallet?
thanks
best regaards

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cculianu** [comment]
I think it would be easier for you and me if you just came to the telegram chat channel so other users can help you:

https://t.me/electroncashwallet

**Comment by anonymeenligne** [comment]
So i don t know if you understand my problem but the technical support of electrum is helping me!!
i JUST NEED my private key for the legacy adress i convert to send bitcoin on my electron-cash wallet by mistake because there are not bitcoincash
thanks
best regards

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by anonymeenligne** [comment]
GREAT NEWS
i recovered them in an electrum wallet with the seed and the legacy
great
thanks for your help

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request closed without merging**
